Change version to preview.3

diff --git a/utils/make-tar b/utils/make-tar
--- a/utils/make-tar
+++ b/utils/make-tar
@@ -6,6 +6,14 @@ then
     echo "ERROR: please supply version parameter, e.g. 1.5.1 [git|local]"
     exit 1
 fi
+
+if echo $1 | grep -- '-'
+then
+    echo "ERROR: only a release version number is accepted, for example 2.6.5"
+    exit 1
+fi
+
+
 version="$1"
 source="$2"
 
